// flow-typed signature: 1b844e83e58dd683c0374c5152ec809f
// flow-typed version: <<STUB>>/contentful_v^5.1.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'contentful'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'contentful' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'contentful/dist/contentful.browser' {
  declare module.exports: any;
}

declare module 'contentful/dist/contentful.browser.min' {
  declare module.exports: any;
}

declare module 'contentful/dist/contentful.legacy' {
  declare module.exports: any;
}

declare module 'contentful/dist/contentful.legacy.min' {
  declare module.exports: any;
}

declare module 'contentful/dist/contentful.node' {
  declare module.exports: any;
}

declare module 'contentful/dist/contentful.node.min' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/contentful' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/create-contentful-api' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/create-global-options' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/entities/asset' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/entities/content-type' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/entities/entry' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/entities/index' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/entities/space' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/mixins/stringify-safe' {
  declare module.exports: any;
}

declare module 'contentful/dist/es-modules/paged-sync' {
  declare module.exports: any;
}

declare module 'contentful/tonic-example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'contentful/dist/contentful.browser.js' {
  declare module.exports: $Exports<'contentful/dist/contentful.browser'>;
}
declare module 'contentful/dist/contentful.browser.min.js' {
  declare module.exports: $Exports<'contentful/dist/contentful.browser.min'>;
}
declare module 'contentful/dist/contentful.legacy.js' {
  declare module.exports: $Exports<'contentful/dist/contentful.legacy'>;
}
declare module 'contentful/dist/contentful.legacy.min.js' {
  declare module.exports: $Exports<'contentful/dist/contentful.legacy.min'>;
}
declare module 'contentful/dist/contentful.node.js' {
  declare module.exports: $Exports<'contentful/dist/contentful.node'>;
}
declare module 'contentful/dist/contentful.node.min.js' {
  declare module.exports: $Exports<'contentful/dist/contentful.node.min'>;
}
declare module 'contentful/dist/es-modules/contentful.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/contentful'>;
}
declare module 'contentful/dist/es-modules/create-contentful-api.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/create-contentful-api'>;
}
declare module 'contentful/dist/es-modules/create-global-options.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/create-global-options'>;
}
declare module 'contentful/dist/es-modules/entities/asset.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/entities/asset'>;
}
declare module 'contentful/dist/es-modules/entities/content-type.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/entities/content-type'>;
}
declare module 'contentful/dist/es-modules/entities/entry.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/entities/entry'>;
}
declare module 'contentful/dist/es-modules/entities/index.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/entities/index'>;
}
declare module 'contentful/dist/es-modules/entities/space.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/entities/space'>;
}
declare module 'contentful/dist/es-modules/mixins/stringify-safe.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/mixins/stringify-safe'>;
}
declare module 'contentful/dist/es-modules/paged-sync.js' {
  declare module.exports: $Exports<'contentful/dist/es-modules/paged-sync'>;
}
declare module 'contentful/tonic-example.js' {
  declare module.exports: $Exports<'contentful/tonic-example'>;
}
