// flow-typed signature: b4a87fe94593d156858a512ec3b758be
// flow-typed version: <<STUB>>/react-app-rewire-hot-loader_v^1.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-hot-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-app-rewire-hot-loader/index' {
  declare module.exports: $Exports<'react-app-rewire-hot-loader'>;
}
declare module 'react-app-rewire-hot-loader/index.js' {
  declare module.exports: $Exports<'react-app-rewire-hot-loader'>;
}
